/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eddy_eimagepro_core_ImageProcessor */

#ifndef _Included_com_eddy_eimagepro_core_ImageProcessor
#define _Included_com_eddy_eimagepro_core_ImageProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eddy_eimagepro_core_ImageProcessor
 * Method:    grayImage
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_eddy_eimagepro_core_ImageProcessor_grayImage
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_eddy_eimagepro_core_ImageProcessor
 * Method:    binarizationImage
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_eddy_eimagepro_core_ImageProcessor_binarizationImage
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
